# Setup: Generate Sample Dataset

This cell creates the required folder structure (`data/raw/` and `data/processed/`) relative to the notebook, and generates the sample CSV dataset with missing values. 
This ensures the dataset is ready for cleaning functions and saves it to `data/raw/sample_data.csv`.

In [ ]:
# --- packages this notebook needs (uncomment and run once, then re-comment) ---
# !pip install numpy
# !pip install pandas

In [1]:
# --- files this notebook needs (run me first - I only report, I change nothing) ---
from pathlib import Path

ROOT = Path.cwd()          # notebooks are meant to be run from their own folder
CHECKS = [
    ("src/cleaning.py", "NEEDED", "YOU write this in the homework - the import fails until you do"),
]

print(f"Looking in: {ROOT}\n")
missing = 0
for rel, kind, note in CHECKS:
    here = (ROOT / rel).exists()
    if not here and kind == "NEEDED":
        missing += 1
    print(f"  [{'OK ' if here else 'MISS'}]  {kind:<8}  {rel:<34}  {note}")

if missing:
    print(f"\n{missing} needed file(s) missing. Put them at the paths above, relative to:\n  {ROOT}")
    print("If that folder looks wrong, you are running the notebook from the wrong place.")
else:
    print("\nAll needed files present.")

Looking in: e:\研究生\bootcamp\bootcamp_aixuan_liu\homework\homework06

  [OK ]  NEEDED    src/cleaning.py                     YOU write this in the homework - the import fails until you do

All needed files present.

In [2]:
import os
import pandas as pd
import numpy as np

# Define folder paths relative to this notebook
raw_dir = 'data/raw'
processed_dir = 'data/processed'

# Create folders if they don't exist
os.makedirs(raw_dir, exist_ok=True)
os.makedirs(processed_dir, exist_ok=True)

# Define the sample data
data = {
    'age': [34, 45, 29, 50, 38, np.nan, 41],
    'income': [55000, np.nan, 42000, 58000, np.nan, np.nan, 49000],
    'score': [0.82, 0.91, np.nan, 0.76, 0.88, 0.65, 0.79],
    'zipcode': ['90210', '10001', '60614', '94103', '73301', '12345', '94105'],
    'city': ['Beverly', 'New York', 'Chicago', 'SF', 'Austin', 'Unknown', 'San Francisco'],
    'extra_data': [np.nan, 42, np.nan, np.nan, np.nan, 5, np.nan]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to CSV in raw data folder
csv_path = os.path.join(raw_dir, 'sample_data.csv')
if not os.path.exists(csv_path):
    df.to_csv(csv_path, index=False)
    print(f'Sample dataset created and saved to {csv_path}')
else:
    print(f'File already exists at {csv_path}. Skipping CSV creation to avoid overwrite.')

Sample dataset created and saved to data/raw\sample_data.csv

# Homework Starter — Stage 6: Data Preprocessing
Use this notebook to apply your cleaning functions and save processed data.

In [3]:
import pandas as pd

# Uncomment once you have written src/cleaning.py (see the homework sheet).
# Until then this import fails - the module is yours to create.
from src import cleaning

## Load Raw Dataset

In [4]:
df = pd.read_csv('data/raw/sample_data.csv')
df.head()

    age   income  score  zipcode      city  extra_data
0  34.0  55000.0   0.82    90210   Beverly         NaN
1  45.0      NaN   0.91    10001  New York        42.0
2  29.0  42000.0    NaN    60614   Chicago         NaN
3  50.0  58000.0   0.76    94103        SF         NaN
4  38.0      NaN   0.88    73301    Austin         NaN

In [5]:
original_df = df.copy()

In [6]:
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
age           1
income        3
score         1
zipcode       0
city          0
extra_data    5
dtype: int64

## Apply Cleaning Functions

In [10]:
# Step 1: Fill missing numeric values with medians
df = cleaning.fill_missing_median(
    df,
    ['age', 'income', 'score']
)

# Step 2: Drop columns with more than 50% missing values
df = cleaning.drop_missing(
    df,
    threshold=0.5
)

# Step 3: Normalize numeric features using min-max scaling
df = cleaning.normalize_data(
    df,
    ['age', 'income', 'score']
)

print("Cleaned dataset:")
display(df)

Cleaned dataset:

        age  income     score  zipcode           city
0  0.238095  0.8125  0.653846    90210        Beverly
1  0.761905  0.6250  1.000000    10001       New York
2  0.000000  0.0000  0.596154    60614        Chicago
3  1.000000  1.0000  0.423077    94103             SF
4  0.428571  0.6250  0.884615    73301         Austin
5  0.500000  0.6250  0.000000    12345        Unknown
6  0.571429  0.4375  0.538462    94105  San Francisco

In [11]:
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
age        0
income     0
score      0
zipcode    0
city       0
dtype: int64

In [14]:
## Original vs Cleaned Data
print("Original dataset:")
display(original_df)

print("Cleaned dataset:")
display(df)

Original dataset:

    age   income  score  zipcode           city  extra_data
0  34.0  55000.0   0.82    90210        Beverly         NaN
1  45.0      NaN   0.91    10001       New York        42.0
2  29.0  42000.0    NaN    60614        Chicago         NaN
3  50.0  58000.0   0.76    94103             SF         NaN
4  38.0      NaN   0.88    73301         Austin         NaN
5   NaN      NaN   0.65    12345        Unknown         5.0
6  41.0  49000.0   0.79    94105  San Francisco         NaN

Cleaned dataset:

        age  income     score  zipcode           city
0  0.238095  0.8125  0.653846    90210        Beverly
1  0.761905  0.6250  1.000000    10001       New York
2  0.000000  0.0000  0.596154    60614        Chicago
3  1.000000  1.0000  0.423077    94103             SF
4  0.428571  0.6250  0.884615    73301         Austin
5  0.500000  0.6250  0.000000    12345        Unknown
6  0.571429  0.4375  0.538462    94105  San Francisco

In [15]:
print("Original shape:", original_df.shape)
print("Cleaned shape:", df.shape)

Original shape: (7, 6)
Cleaned shape: (7, 5)

In [16]:
comparison = pd.DataFrame({
    "Original Missing": original_df.isnull().sum(),
    "Cleaned Missing": df.isnull().sum()
})

display(comparison)

            Original Missing  Cleaned Missing
age                        1              0.0
city                       0              0.0
extra_data                 5              NaN
income                     3              0.0
score                      1              0.0
zipcode                    0              0.0

## Cleaning Assumptions

1. Missing values in continuous numeric variables (`age`, `income`, and `score`) are assumed to be reasonably represented by the median of the observed values.

2. Median imputation is used instead of mean imputation because the median is less sensitive to extreme values.

3. Columns with more than 50% missing values are considered to contain insufficient information for reliable analysis and are removed.

4. The `extra_data` column is removed because more than half of its observations are missing.

5. `age`, `income`, and `score` are normalized using min-max scaling so that their values fall between 0 and 1.

6. `zipcode` is not normalized because it is an identifier rather than a continuous numerical measurement.

7. `city` is retained as a categorical variable and is not normalized.

## Reflection and Tradeoffs

The preprocessing strategy preserves as many observations as possible while reducing the impact of missing data. Median imputation allows rows with missing numeric values to remain in the dataset instead of being deleted.

However, median imputation also introduces estimated values and may reduce the natural variation of the data. Dropping the `extra_data` column removes a feature that could potentially contain useful information, but its high proportion of missing values makes it difficult to use reliably.

Min-max normalization makes numerical variables easier to compare and can be useful for machine learning algorithms that are sensitive to feature scale. However, normalization changes the original units of the variables, so interpretation must be performed carefully.

## Save Cleaned Dataset

In [17]:
df.to_csv(
    'data/processed/sample_data_cleaned.csv',
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.